### ISSUE TITLE
Fall 2018 plan

### ISSUE THREAD

**Issue by Haaxor1689** [Haaxor1689/PixelMonasteryScript#1]
## 1. milestone 27.9.
- [x] Prepare semester plan
- [x] Consult current state of font
- [x] Check UTF symbol group coverage

## 2. consultations 4.10.
- [ ] Implement feedback
- [ ] Generate missing symbols

## 3. consultations 11.10.
- [ ] Basic alphabet for thinner paragraph font style

## 4. consultations 18.10.
- [ ] Additional symbols

## 5. consultations 25.10.
- [ ] All ASCII symbols

## 6. consultations 1.11.
- [ ] Accents and other special symbols

## 7. consultations 8.11.
- [ ] Vectorize bitmap symbols

## 8. consultations 15.11.
- [ ] Symbols with accents
- [ ] Ligatures?
- [ ] Start kerning groups

## 9. consultations 22.11.
- [ ] Kerning

## 10. consultations 29.11.
- [ ] Polishing

## 11. consultations 6.12.
- [ ] Polishing

## 12. consultations 13.12.
- [ ] Polishing
